In [1]:
from tensorflow import keras
from keras.datasets import mnist
from keras import models
from keras import layers

In [2]:
(train_images,train_labels),(test_images,test_labels)=mnist.load_data()

11501568/11490434 [==============================] - 1s 0us/step


In [3]:
train_images.shape

(60000, 28, 28)

In [4]:
len(train_labels)

60000

In [5]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [6]:
test_images.shape

(10000, 28, 28)

In [7]:
len(test_labels)

10000

# NEURAL NETWORK

In [8]:
network=models.Sequential()

2022-12-11 11:58:22.588541: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


In [9]:
network.add(layers.Dense(512,activation='relu', input_shape=(28 * 28,)))

In [10]:
network.add(layers.Dense(10,activation='softmax'))

In [11]:
network.compile(optimizer='rmsprop',
               loss = 'categorical_crossentropy',
               metrics=['accuracy'])

**Preparing the image data**

In [12]:
train_images.shape

(60000, 28, 28)

In [13]:
train_images=train_images.reshape((60000,28*28))
train_images.shape

(60000, 784)

**Scaling the data**

In [14]:
train_images=train_images.astype('float32')/255
train_images

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

**Re-shaping & Scaling**

In [15]:
test_images=test_images.reshape((10000,28*28))

In [16]:
test_images=test_images.astype('float32')/255
test_images

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

***Train_labels as categories***

In [17]:
from tensorflow.keras.utils import to_categorical

In [18]:
train_labels =to_categorical(train_labels)
train_labels

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

**test_labels as categories**

In [19]:
test_labels =to_categorical(test_labels)
test_labels

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

***fitting the model to its train data***

In [20]:
network.fit(train_images,train_labels, epochs=5,batch_size=128)

2022-12-11 11:58:24.252533: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)


Epoch 1/5
469/469 [==============================] - 4s 7ms/step - loss: 0.2560 - accuracy: 0.9251
Epoch 2/5
469/469 [==============================] - 3s 7ms/step - loss: 0.1033 - accuracy: 0.9697
Epoch 3/5
469/469 [==============================] - 3s 7ms/step - loss: 0.0685 - accuracy: 0.9795
Epoch 4/5
469/469 [==============================] - 4s 9ms/step - loss: 0.0502 - accuracy: 0.9844
Epoch 5/5
469/469 [==============================] - 3s 7ms/step - loss: 0.0370 - accuracy: 0.9883


**Test data performance**

In [21]:
test_loss, test_acc=network.evaluate(test_images,test_labels)

313/313 [==============================] - 1s 2ms/step - loss: 0.0696 - accuracy: 0.9785


In [22]:
print('test_acc:A',test_acc)

test_acc:A 0.9785000085830688
